// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionItem: typeof import('./src/components/actionItem.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    DarkModeToggle: typeof import('./src/components/ui/DarkModeToggle.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LottieAnimation: typeof import('vue3-lottie')['Vue3Lottie']
    MobileBottomBar: typeof import('./src/components/layout/MobileBottomBar.vue')['default']
    MobileNavbar: typeof import('./src/components/layout/mobileNavbar.vue')['default']
    MobileTopBar: typeof import('./src/components/layout/MobileTopBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
